export const tools = [
  {
    slug: "ai-tiktok-video-generator",
    title: "AI TikTok Video Generator",
    description: "Create viral TikTok videos in seconds using AI. No filming or editing required.",
    heroTitle: "AI TikTok Video Generator",
    heroDescription: "Generate engaging TikTok videos with AI scripts, voices, and visuals. Perfect for scaling your TikTok presence without showing your face.",
  },
  {
    slug: "ai-youtube-shorts-generator",
    title: "AI YouTube Shorts Generator",
    description: "Grow your YouTube channel with AI-generated Shorts. Fast, easy, and effective.",
    heroTitle: "AI YouTube Shorts Generator",
    heroDescription: "Turn any idea into a vertical YouTube Short. Our AI handles the script, voiceover, and visual selection for maximum engagement.",
  },
  {
    slug: "ai-instagram-reels-generator",
    title: "AI Instagram Reels Generator",
    description: "Make stunning Instagram Reels with AI. Captivate your audience effortlessly.",
    heroTitle: "AI Instagram Reels Generator",
    heroDescription: "Create aesthetic and high-performing Instagram Reels. Leverage AI to produce content that stands out in the feed and Explore page.",
  },
  {
    slug: "ai-pixar-video-generator",
    title: "AI Pixar Video Generator",
    description: "Create 3D animation style videos like Pixar. Bring your stories to life.",
    heroTitle: "AI Pixar Video Generator",
    heroDescription: "Generate videos with the charming 3D aesthetic of Pixar animations. Perfect for storytelling, ads, and social media content.",
  },
  {
    slug: "ai-anime-video-generator",
    title: "AI Anime Video Generator",
    description: "Turn your ideas into beautiful anime-style videos. Unleash your creativity.",
    heroTitle: "AI Anime Video Generator",
    heroDescription: "Create stunning anime-style visuals and stories. Our AI captures the essence of anime art to bring your concepts to life.",
  },
  {
    slug: "ai-image-to-video",
    title: "AI Image to Video",
    description: "Animate your static images into dynamic videos using advanced AI.",
    heroTitle: "AI Image to Video",
    heroDescription: "Breathe life into your photos and artwork. Our AI analyzes your images and generates natural motion and cinematic transitions.",
  },
  {
    slug: "prompt-to-video",
    title: "Prompt to Video",
    description: "Enter a prompt and watch AI generate a complete video for you.",
    heroTitle: "Prompt to Video",
    heroDescription: "The simplest way to create video. Describe what you want to see, and our AI will build a complete video from scratch.",
  },
  {
    slug: "script-to-video-ai",
    title: "Script to Video AI",
    description: "Turn your scripts into professional videos with AI-powered visuals and voices.",
    heroTitle: "Script to Video AI",
    heroDescription: "Provide a script, and we'll provide the video. Our AI automatically matches your text with relevant visuals and voiceovers.",
  },
  {
    slug: "text-to-video",
    title: "Text to Video",
    description: "Transform any text content into engaging video presentations.",
    heroTitle: "Text to Video",
    heroDescription: "Convert blog posts, articles, or notes into compelling videos. Perfect for repurposing content and reaching new audiences.",
  },
  {
    slug: "ai-video-generator",
    title: "AI Video Generator",
    description: "The all-in-one AI tool for creating high-quality videos for any purpose.",
    heroTitle: "AI Video Generator",
    heroDescription: "A versatile video creation tool powered by AI. From marketing to education, generate the perfect video for any use case.",
  },
  {
    slug: "short-video-maker",
    title: "Short Video Maker",
    description: "The fastest way to create short-form content for all social platforms.",
    heroTitle: "Short Video Maker",
    heroDescription: "Optimized for short-form content. Create quick, punchy videos that grab attention and drive results on mobile-first platforms.",
  },
  {
    slug: "social-media-video-maker",
    title: "Social Media Video Maker",
    description: "Create social media videos that drive engagement and grow your brand.",
    heroTitle: "Social Media Video Maker",
    heroDescription: "Master social media with videos designed for growth. Our tool helps you create content tailored for every major social network.",
  },
  {
    slug: "faceless-ai-video-generator",
    title: "Faceless AI Video Generator",
    description: "Create videos without showing your face. Maintain privacy while building a brand.",
    heroTitle: "Faceless AI Video Generator",
    heroDescription: "Create videos without showing your face, recording footage, or editing manually. Start with a topic and generate a complete faceless short.",
  },
  {
    slug: "ai-motivational-video-generator",
    title: "AI Motivational Video Generator",
    description: "Generate inspiring motivational videos with powerful visuals and voices.",
    heroTitle: "AI Motivational Video Generator",
    heroDescription: "Inspire your audience with AI-generated motivational content. Combine moving scripts with cinematic visuals and epic voiceovers.",
  },
  {
    slug: "ai-horror-story-video-generator",
    title: "AI Horror Story Video Generator",
    description: "Create spine-chilling horror story videos with eerie AI-generated content.",
    heroTitle: "AI Horror Story Video Generator",
    heroDescription: "Tell terrifying tales with AI. Generate spooky visuals and suspenseful narrations for your horror-themed channel or project.",
  },
  {
    slug: "ai-true-crime-video-generator",
    title: "AI True Crime Video Generator",
    description: "Produce engaging true crime videos with AI-assisted research and visuals.",
    heroTitle: "AI True Crime Video Generator",
    heroDescription: "Dive into mystery with AI. Create compelling true crime stories with detailed scripts and atmospheric visual recreations.",
  },
  {
    slug: "talking-object",
    title: "Talking Object",
    description: "Make any object talk with AI-powered animation and voice synchronization.",
    heroTitle: "Talking Object",
    heroDescription: "Give a voice to the inanimate. Our AI allows you to animate any object and sync its 'speech' with a voiceover.",
  },
  {
    slug: "educational-video-maker",
    title: "Educational Video Maker",
    description: "Create informative and clear educational videos with ease using AI.",
    heroTitle: "Educational Video Maker",
    heroDescription: "Simplify complex topics. Use AI to generate educational content that is easy to understand, visually engaging, and informative.",
  },
];
